### ISSUE TITLE
Driver crashes since laravel 5.8.19

### ISSUE THREAD

**Issue by tim-hanssen** [monospice/laravel-redis-sentinel-drivers#21] opened 2019-06-08 13:45 UTC
Since the laravel 5.8.19 release we get an connection error when using a sentinel connection.

`
ConnectionException {#649 ▼
  -connection: StreamConnection {#641 ▶}
  #message: "Connection refused [tcp://127.0.0.1:6379]"
  #code: 111
  #file: "/data/www/default/vendor/predis/predis/src/Connection/AbstractConnection.php"
  #line: 155
  trace: {▶}
}`

Any suggestions on how we could fix it?

**Comment by cyrossignol** [comment] 2019-06-11 05:47
Hi @tim-hanssen, I'm having trouble reproducing this issue. I tried with Laravel versions 5.8.19 and 5.8.21. Based on that error, it looks like the config changed or the application may not be picking up the package's service provider after the upgrade. 

We can check that the service provider loaded by running:

```php
dd(app('redis-sentinel'));
```

We'll see the following error message if the service provider did not load:

> ReflectionException with message 'Class redis-sentinel does not exist'

**Comment by mathieutu** [comment] 2019-06-13 10:40
I think this will be resolved in next release: https://github.com/laravel/framework/pull/28830 😉

Please tell me if not.

**Comment by cyrossignol** [comment] 2019-06-13 19:27
@tim-hanssen @mathieutu Thanks. After reading through your PRs to laravel/framework, I don't think this is an issue for these drivers. This is an independent package that provides enhanced Sentinel support and parses the configuration using a separate routine. It doesn't call the affected code in Laravel's standard `RedisManager` class. 

Are you using this package in your projects?

**Comment by mathieutu** [comment] 2019-06-13 19:42
I think this issue has nothing related with this package, it's about a bug in the redis manager, that the PR will solve. 

So this can be close when the PR will be merged and we that we have confirmation that this is linked.

**Comment by cyrossignol** [comment] 2019-09-12 15:43
The PRs were merged, and I don't see any actionable items related to this package. Please comment if you think otherwise 🙂

**Closed as completed by cyrossignol** 2019-09-12 15:43 UTC
Labels: question
